# --- DQN specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

# Not sure whether episode vs parallel matters, but parallel should be faster
# runner: "episode"
runner: "parallel"
batch_size_run: 8

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

mac: "gan_mac" # Adversarial controller

# use the Q_Learner to train
learner: "gan_learner"
gan_hidden_size: 100

# Args for loaded model, TODO make args dynamically load from params.json
agent_output_type: "q"
double_q: True
mixer: # Mixer becomes None

name: "adv_dqn_gen"

# CUSTOM:
save_model: True # Save the models to disk
save_model_interval: 500000 # Save models after this many timesteps

# Path to trained QMIX policy for N-1 agents
trained_agent_policy: "results/models/qmix_2s3z/2000079"
trained_adv_policy: "results/models/adv_dqn_parallel/2001012"
